version: '3'
services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - 5002:3333
    volumes:
      - .:/usr/app
      - /home/gfaraujo/simtest:/external
      - /usr/app/node_modules
